org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

mod_id=immersive_weathering
mod_name=Immersive Weathering
mod_version=1.21.1-2.0.5
mod_group_id=com.ordana
mod_license=LGPLv3
mod_authors=Ordana, MehVahdJukaar, Keybounce
mod_logo_file=icon.png
mod_description=An abundance of new natural systems to make your world feel more alive than ever.

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.226
loader_version_range=[1,)

emi_version=1.1.12+1.20.1
moonlight_version=1.21.1-3.0.5


