{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight-fabric",
    "version": "1.19.2-2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.21-fabric.jar",
          "url": "moonlight-fabric-1.19.2-2.1.21-fabric.jar",
          "size": 756723,
          "sha512": "a91452df37ec71774be8b446b1103436911c7b7cc3013a599550874b9570ba53dfdd3c2034527616325080a164785ce7fc4c31f10a6911165b010a4a7a333bb8",
          "sha256": "b65491e16868fa3c60bfe4a52111d400169a5d8206e7ad5b4c61eb3bcb72e3ed",
          "sha1": "d37bd6797f43a0713d88ac1a49c4bfe568d76527",
          "md5": "d4bde94cc39f58607266871e16b28ddd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.59.0+1.19.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "7.0.72"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "map-atlases-436298",
          "version": {
            "requires": "3953555"
          }
        },
        {
          "group": "curse.maven",
          "module": "yacl-667299",
          "version": {
            "requires": "3987709"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.21-fabric.jar",
          "url": "moonlight-fabric-1.19.2-2.1.21-fabric.jar",
          "size": 756723,
          "sha512": "a91452df37ec71774be8b446b1103436911c7b7cc3013a599550874b9570ba53dfdd3c2034527616325080a164785ce7fc4c31f10a6911165b010a4a7a333bb8",
          "sha256": "b65491e16868fa3c60bfe4a52111d400169a5d8206e7ad5b4c61eb3bcb72e3ed",
          "sha1": "d37bd6797f43a0713d88ac1a49c4bfe568d76527",
          "md5": "d4bde94cc39f58607266871e16b28ddd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-fabric-1.19.2-2.1.21-sources.jar",
          "url": "moonlight-fabric-1.19.2-2.1.21-sources.jar",
          "size": 424650,
          "sha512": "4bcb0fe890eec9ed7ab523a08e765a31a0f50156e6671aa557b6c7237731d7889255668a5847793126b65db9be02a427d2f7f04ac282f923f71a154e60ad1740",
          "sha256": "2d3ec32e5fe6b6052780ad730c0a5f4d885f2aa19eae6a8634f41cd69c9fc97d",
          "sha1": "a92e4084a268cb287e4aaf29a576392c68623d69",
          "md5": "201a046ea5ed55874b4693cb72c29f25"
        }
      ]
    }
  ]
}
