{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight",
    "version": "1.19.2-2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.21.jar",
          "url": "moonlight-1.19.2-2.1.21.jar",
          "size": 591163,
          "sha512": "079c9796952aee9bb5d0a0377dc0a7d0af64aeff40e65c0fbae54e601576f6df8273bedbfc76504594a2b0f3c37516b76eb7001a6ccb35fadaf89ebbd2bc3d7a",
          "sha256": "8d18b0fdd1adbf3891e032bbd94f934c899e7e5581c08766ca8bc5e05a61479f",
          "sha1": "79e969da94f2e70716e54d882668de72db47d0a6",
          "md5": "94f894daf128dc866ca30be8e37ed211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.21.jar",
          "url": "moonlight-1.19.2-2.1.21.jar",
          "size": 591163,
          "sha512": "079c9796952aee9bb5d0a0377dc0a7d0af64aeff40e65c0fbae54e601576f6df8273bedbfc76504594a2b0f3c37516b76eb7001a6ccb35fadaf89ebbd2bc3d7a",
          "sha256": "8d18b0fdd1adbf3891e032bbd94f934c899e7e5581c08766ca8bc5e05a61479f",
          "sha1": "79e969da94f2e70716e54d882668de72db47d0a6",
          "md5": "94f894daf128dc866ca30be8e37ed211"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.1.21-sources.jar",
          "url": "moonlight-1.19.2-2.1.21-sources.jar",
          "size": 340692,
          "sha512": "b045d678399f01f269c3643b009b75fa1d5e42d391c8550eab3c85c67706efcce4890e673410fd0888b8f015efbbf4294ce36c9b4b35eedbc14db6b0cafe097b",
          "sha256": "e81c024568b5354370e20fa303145ec491e38604a3acb805b090c73aacd4bbc6",
          "sha1": "0d485bbe2db256f791ba145a3b00291600d5d70d",
          "md5": "8c3cf34ae0f82eadc21f54841c0a9d97"
        }
      ]
    }
  ]
}
