{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight",
    "version": "1.19.2-2.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.40.jar",
          "url": "moonlight-1.19.2-2.0.40.jar",
          "size": 564813,
          "sha512": "872ac3fbabf52b15716be87d294cf93eae0043c5ae00103ae988ad371e2b22a3058975dddb077d1793f70b3e599f81f7b9b011ae28844e1244725ea73a98dc09",
          "sha256": "9f7458919d9b4968f165facf37b07b4a192d6dd58d58d2e07e1352b5e409ac00",
          "sha1": "c0cfe655afb9c496b9ae2fd821f26832d6b1d588",
          "md5": "de02e77da45cedc96179c2d0d1d9113f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.40.jar",
          "url": "moonlight-1.19.2-2.0.40.jar",
          "size": 564813,
          "sha512": "872ac3fbabf52b15716be87d294cf93eae0043c5ae00103ae988ad371e2b22a3058975dddb077d1793f70b3e599f81f7b9b011ae28844e1244725ea73a98dc09",
          "sha256": "9f7458919d9b4968f165facf37b07b4a192d6dd58d58d2e07e1352b5e409ac00",
          "sha1": "c0cfe655afb9c496b9ae2fd821f26832d6b1d588",
          "md5": "de02e77da45cedc96179c2d0d1d9113f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-1.19.2-2.0.40-sources.jar",
          "url": "moonlight-1.19.2-2.0.40-sources.jar",
          "size": 328488,
          "sha512": "0511062af60db7b9096fd2d2e91d7a21dfb7c666502b601427c853828643d263cb909bdf82fe31130b97b25b7ad56439de3c041149754b30467be344f6fedb9e",
          "sha256": "ba9cd0f5032c9509f145415618dd08456e421263d134dea4a8ecb24313e3b461",
          "sha1": "964b8f9c1a4a73a2f595d2bb4368015354f90731",
          "md5": "f29cc2865140bc0dcc0bc6dd23a1d940"
        }
      ]
    }
  ]
}
