{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight-forge",
    "version": "1.19.2-2.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.1.21-forge.jar",
          "url": "moonlight-forge-1.19.2-2.1.21-forge.jar",
          "size": 729333,
          "sha512": "f0e0e9bf83115ea698b76733f3d4b95177d69a8269e320f4dc14ceb369edd08f14a101940079aa59cb10d3fa34e352ff7935d972a9afa62856f6cedc49452529",
          "sha256": "dcb353d1123b4d0b6bb6197274d26dd45b5fc286cc42ea4f06b49e9a4adc0556",
          "sha1": "7d59f5c70c8c769acf0a0ee588405074815ca4c1",
          "md5": "4c3770280678d7330bc6c81a5d61f27c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "4011355"
          }
        },
        {
          "group": "curse.maven",
          "module": "map-atlases-forge-519759",
          "version": {
            "requires": "3949437"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.1.21-forge.jar",
          "url": "moonlight-forge-1.19.2-2.1.21-forge.jar",
          "size": 729333,
          "sha512": "f0e0e9bf83115ea698b76733f3d4b95177d69a8269e320f4dc14ceb369edd08f14a101940079aa59cb10d3fa34e352ff7935d972a9afa62856f6cedc49452529",
          "sha256": "dcb353d1123b4d0b6bb6197274d26dd45b5fc286cc42ea4f06b49e9a4adc0556",
          "sha1": "7d59f5c70c8c769acf0a0ee588405074815ca4c1",
          "md5": "4c3770280678d7330bc6c81a5d61f27c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.1.21-sources.jar",
          "url": "moonlight-forge-1.19.2-2.1.21-sources.jar",
          "size": 406103,
          "sha512": "abf7506f1b36a65a33312349be92620df51b2918373cc6ede90f3c95e24c4216c43439b2d3af80ad90f2e9235bd0e3c8262c49574ab0dd708c92b13a335265ad",
          "sha256": "710d95a47cb9493ce2fe8e2d8e6b97e5ba64a0ef5eb8433aaa4f4f998cdd089d",
          "sha1": "266467d41088ad46c0848efe1b5f7630a781e01c",
          "md5": "3ef80377a46c4e49bc8322bca4f4df18"
        }
      ]
    }
  ]
}
