{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mehvahdjukaar",
    "module": "moonlight-forge",
    "version": "1.19.2-2.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.0.39.jar",
          "url": "moonlight-forge-1.19.2-2.0.39.jar",
          "size": 698334,
          "sha512": "79d0abc64bc6f556cf3cd6db23afa013cec00dd5a350b29339bdd5ffcf2d1a454c15aeffbb8afe4dc7e05a4f2993a89ebd79198c0e55b61c9daba5cc04c76377",
          "sha256": "e4f047d1bbb558a63ec7db29f1c98a5d300cfa834e2bec1948967d9c04636489",
          "sha1": "90de68bb89956ef59408d22699a2f2ab9423d568",
          "md5": "d29a4d47a95eae6096f5dbd06c8c4676"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "configured-457570",
          "version": {
            "requires": "4011355"
          }
        },
        {
          "group": "curse.maven",
          "module": "map-atlases-forge-519759",
          "version": {
            "requires": "3949437"
          }
        }
      ],
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.0.39.jar",
          "url": "moonlight-forge-1.19.2-2.0.39.jar",
          "size": 698334,
          "sha512": "79d0abc64bc6f556cf3cd6db23afa013cec00dd5a350b29339bdd5ffcf2d1a454c15aeffbb8afe4dc7e05a4f2993a89ebd79198c0e55b61c9daba5cc04c76377",
          "sha256": "e4f047d1bbb558a63ec7db29f1c98a5d300cfa834e2bec1948967d9c04636489",
          "sha1": "90de68bb89956ef59408d22699a2f2ab9423d568",
          "md5": "d29a4d47a95eae6096f5dbd06c8c4676"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moonlight-forge-1.19.2-2.0.39-sources.jar",
          "url": "moonlight-forge-1.19.2-2.0.39-sources.jar",
          "size": 392042,
          "sha512": "4fdaec6c52c07319ef8b097802841fa3ac49ac7f5fa3edf8ff32f321f1300714ae65ef9e32d23cb242c33db4c01598badfacfbf687b9460b5393c1882813642c",
          "sha256": "f356f159961b457ded3d090dec164a39df9d9c926738d5ce7bf39f61fccd0ab7",
          "sha1": "82959f586204b4fb5c46d50e558d396646b893cd",
          "md5": "506048dd82aab8ea00ae9f744a7b556e"
        }
      ]
    }
  ]
}
